#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed Apr 26 2023 11:45:33
#sha1: 717411
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='DESKTOP-DI75JFP', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 140 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
390,design,log,
#design: #exp: Shams Experiment
#design: #dvn: number_trials,number_flashes,response_key,RT
#design: block_cnt,block_id,trial_cnt,trial_id
390,design,logged,
390,Experiment,started
408,Stimulus,presented,1
1192,Keyboard,received,32,wait
1202,stderr,received,'Traceback (most recent call last):'
1202,stderr,received,'  File "trial_version.py", line 121, in <module>'
1203,stderr,received,"    for c in trials[['FIXATION']]: # c should correspond to the fourth column (FIXATION)"
1203,stderr,received,'  File "C:\\Users\\monik\\anaconda3\\envs\\expyriment\\lib\\site-packages\\pandas\\core\\frame.py", line 3464, in __getitem__'
1206,stderr,received,'    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]'
1206,stderr,received,'  File "C:\\Users\\monik\\anaconda3\\envs\\expyriment\\lib\\site-packages\\pandas\\core\\indexing.py", line 1314, in _get_listlike_indexer'
1211,stderr,received,'    self._validate_read_indexer(keyarr, indexer, axis)'
1212,stderr,received,'  File "C:\\Users\\monik\\anaconda3\\envs\\expyriment\\lib\\site-packages\\pandas\\core\\indexing.py", line 1374, in _validate_read_indexer'
1213,stderr,received,'    raise KeyError(f"None of [{key}] are in the [{axis_name}]")'
1214,stderr,received,'KeyError: "None of [Index([\'FIXATION\'], dtype=\'object\')] are in the [columns]"'
